<a href="https://colab.research.google.com/github/Ravichandran2191/Basic-scripts-Python-mini/blob/main/phonepe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
remote: Enumerating objects: 8891, done.
remote: Counting objects: 100% (8891/8891), done.
remote: Compressing objects: 100% (7400/7400), done.
remote: Total 8891 (delta 2789), reused 7257 (delta 1170), pack-reused 0
Receiving objects: 100% (8891/8891), 2.30 MiB | 11.27 MiB/s, done.
Resolving deltas: 100% (2789/2789), done.

In [ ]:
import pandas as pd
import json
import os
import csv

In [ ]:
import csv

In [ ]:
path='/content/pulse/data/aggregated/transaction/country/india/state/'
Agg_State_list=os.listdir(path)
Agg_State_list

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm={'state':[],'year':[],'quarter':[],'transaction_type':[],'transaction_count':[],'transaction_amount':[]}
for i in Agg_State_list:
  p_i=path+i+'/'
  Agg_yr=os.listdir(p_i)
  for j in Agg_yr:
    p_j=p_i+j+'/'
    Agg_yr_list=os.listdir(p_j)
    for k in Agg_yr_list:
        p_k=p_j+k
        data=open(p_k,'r')
        d=json.load(data)
        for z in d['data']['transactionData']:
          Name=z['name']
          count=z['paymentInstruments'][0]['count']
          amount=z['paymentInstruments'][0]['amount']
          clm['transaction_type'].append(Name)
          clm['transaction_count'].append(count)
          clm['transaction_amount'].append(amount)
          clm['state'].append(i)
          clm['year'].append(j)
          clm['quarter'].append(int(k.strip('.json')))
df1=pd.DataFrame(clm)
df1

,state,year,quarter,transaction_type,transaction_count,transaction_amount
0,telangana,2022,4,Merchant payments,1002521735,4.915560e+11
1,telangana,2022,4,Peer-to-peer payments,694612831,2.393380e+12
2,telangana,2022,4,Recharge & bill payments,121188131,9.213676e+10
3,telangana,2022,4,Financial Services,401838,4.987194e+08
4,telangana,2022,4,Others,782297,6.806806e+08
...,...,...,...,...,...,...
3949,nagaland,2023,2,Peer-to-peer payments,1617109,6.785636e+09
3950,nagaland,2023,2,Merchant payments,727260,1.034148e+09
3951,nagaland,2023,2,Recharge & bill payments,572760,1.972427e+08
3952,nagaland,2023,2,Financial Services,2070,1.698008e+06
3953,nagaland,2023,2,Others,2802,2.675253e+06

In [ ]:
df1.to_csv('z.csv')

In [ ]:
path2='/content/pulse/data/aggregated/user/country/india/state/'
Agg_state2=os.listdir(path2)
Agg_state2

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm2={'state':[],'year':[],'quater':[],'brand':[],'count':[],'percentage':[]}
for x in Agg_state2:
  x_i=path2+x+'/'
  Agg_yr2=os.listdir(x_i)
  for l in Agg_yr2:
    l_i=x_i+l+'/'
    Agg_js=os.listdir(l_i)
    for js in Agg_js:
      j_js=l_i+js
      data2=open(j_js,'r')
      d2=json.load(data2)
      if d2['data']['usersByDevice'] is not None:
        for a in d2['data']['usersByDevice']:
          brand=a['brand']
          count=a['count']
          percentage=a['percentage']
          clm2['brand'].append(brand)
          clm2['count'].append(count)
          clm2['percentage'].append(percentage)
          clm2['state'].append(x)
          clm2['year'].append(l)
          clm2['quater'].append(int(js.strip('.json')))
df2=pd.DataFrame(clm2)
df2

          state  year  quater     brand    count  percentage
0     telangana  2022       1    Xiaomi  5509008    0.248707
1     telangana  2022       1      Vivo  4471684    0.201876
2     telangana  2022       1   Samsung  4003841    0.180755
3     telangana  2022       1      Oppo  2540306    0.114683
4     telangana  2022       1    Realme  1999746    0.090279
...         ...   ...     ...       ...      ...         ...
6727   nagaland  2021       2    Huawei     4355    0.019500
6728   nagaland  2021       2    Gionee     3847    0.017225
6729   nagaland  2021       2      Asus     3569    0.015980
6730   nagaland  2021       2  Micromax     2956    0.013236
6731   nagaland  2021       2    Others    24974    0.111822

[6732 rows x 6 columns]

In [ ]:
df2.to_csv('a.csv')

In [ ]:
path3='/content/pulse/data/map/transaction/hover/country/india/state/'
Agg_map_state=os.listdir(path3)
Agg_map_state

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm3={'stste':[],'year':[],'quater':[],'metric_count':[],'metric_amount':[]}
for m in Agg_map_state:
  m_s=path3+m+'/'
  Agg_map_yr=os.listdir(m_s)
  Agg_map_yr
  for my in Agg_map_yr:
    my_y=m_s+my+'/'
    # print(my_y)
    Agg_map_js=os.listdir(my_y)
    Agg_map_js
    for j in Agg_map_js:
      j_s=my_y+j
      # print(j_s)
      data3=open(j_s,'r')
      d3=json.load(data3)
      for s in d3['data']['hoverDataList']:
        count=s['metric'][0]['count']
        amount=s['metric'][0]['amount']
        clm3['metric_count'].append(count)
        clm3['metric_amount'].append(amount)
        clm3['stste'].append(m)
        clm3['year'].append(my)
        clm3['quater'].append(int(j.strip('.json')))
df3=pd.DataFrame(clm3)
df3

           stste  year  quater  metric_count  metric_amount
0      telangana  2022       4       3435861   7.851530e+09
1      telangana  2022       4      21928009   4.551753e+10
2      telangana  2022       4       7324178   1.473396e+10
3      telangana  2022       4      13693915   2.753138e+10
4      telangana  2022       4       6929973   1.355850e+10
...          ...   ...     ...           ...            ...
16095   nagaland  2023       2         76278   2.743509e+08
16096   nagaland  2023       2         47839   1.404037e+08
16097   nagaland  2023       2       1735282   4.577152e+09
16098   nagaland  2023       2         46870   1.402943e+08
16099   nagaland  2023       2        106988   2.845162e+08

[16100 rows x 5 columns]

In [ ]:
df3.to_csv('s.csv')

In [ ]:
path4='/content/pulse/data/map/user/hover/country/india/state/'
Agg_map_s4=os.listdir(path4)
Agg_map_s4

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm4={'state':[],'year':[],'quter':[],'district':[],'registeredUsers':[],'appOpens':[]}
for s4 in Agg_map_s4:
  s4_4=path4+s4+'/'
  Agg_y4=os.listdir(s4_4)
  Agg_y4
  for y4 in Agg_y4:
    y4_4=s4_4+y4+'/'
    Agg_j4=os.listdir(y4_4)
    Agg_j4
    for j4 in Agg_j4:
      j4_4= y4_4+j4
      data4=open(j4_4,'r')
      d4=json.load(data4)
      for z4 in d4['data']['hoverData']:
        district=z4
        registeredUsers=d4['data']['hoverData'][z4]['registeredUsers']
        appOpens=d4['data']['hoverData'][z4]['appOpens']
        clm4['district'].append(district)
        clm4['registeredUsers'].append(registeredUsers)
        clm4['appOpens'].append(appOpens)
        clm4['state'].append(s4)
        clm4['year'].append(y4)
        clm4['quter'].append(int(j4.strip('.json')))
df4=pd.DataFrame(clm4)
df4

,state,year,quter,district,registeredUsers,appOpens
0,telangana,2022,4,narayanpet district,164467,13004567
1,telangana,2022,4,nalgonda district,793688,62529082
2,telangana,2022,4,jangaon district,268072,24657265
3,telangana,2022,4,bhadradri kothagudem district,542203,35537846
4,telangana,2022,4,warangal rural district,301876,21240770
...,...,...,...,...,...,...
16099,nagaland,2023,2,tuensang district,15272,3253051
16100,nagaland,2023,2,peren district,7407,2074213
16101,nagaland,2023,2,dimapur district,159224,4241175
16102,nagaland,2023,2,zunheboto district,10327,1695437
16103,nagaland,2023,2,wokha district,16076,3359928

In [ ]:
df4.to_csv('z4.csv')

In [ ]:
from pprint import pprint

In [ ]:
# data4=open('/content/pulse/data/map/user/hover/country/india/state/andaman-&-nicobar-islands/2018/1.json','r')
# d4=json.load(data4)
# pprint(d4)

In [ ]:
for i in d4['data']['hoverData']:
  print(i)
  print(d4['data']['hoverData'][i]['registeredUsers'])

north and middle andaman district
632
south andaman district
5846
nicobars district
262

In [ ]:
for i in d4:
  print(i)

success
code
data
responseTimestamp

In [ ]:
path5='/content/pulse/data/top/transaction/country/india/state/'
Agg_s5=os.listdir(path5)
Agg_s5

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm5={'state':[],'year':[],'quter':[],'district':[],'metric_count':[],'metric_amount':[]}
for s5 in Agg_s5:
  s5_5=path5+s5+'/'
  Agg_y5=os.listdir(s5_5)
  for y5 in Agg_y5:
    y5_5=s5_5+y5+'/'
    # print(y5_5)
    Agg_j5=os.listdir(y5_5)
    for j5 in Agg_j5:
      j5_5=y5_5+j5
      data5=open(j5_5,'r')
      d5=json.load(data5)
      for g in d5['data']['districts']:
        dist=g['entityName']
        count=g['metric']['count']
        amount=g['metric']['amount']
        clm5['district'].append(dist)
        clm5['metric_count'].append(count)
        clm5['metric_amount'].append(amount)
        clm5['state'].append(s5)
        clm5['year'].append(y5)
        clm5['quter'].append(int(j5.strip('.json')))
df5=pd.DataFrame(clm5)
df5

          state  year  quter            district  metric_count  metric_amount
0     telangana  2022      4           hyderabad    1133829812   1.753799e+12
1     telangana  2022      4          rangareddy     191136402   2.957737e+11
2     telangana  2022      4  medchal malkajgiri     151514969   2.377269e+11
3     telangana  2022      4          sangareddy      38000808   6.464995e+10
4     telangana  2022      4      warangal urban      29269688   5.799118e+10
...         ...   ...    ...                 ...           ...            ...
6507   nagaland  2023      2            tuensang         76278   2.743509e+08
6508   nagaland  2023      2                phek         73829   2.384209e+08
6509   nagaland  2023      2               peren         47839   1.404037e+08
6510   nagaland  2023      2           zunheboto         46870   1.402943e+08
6511   nagaland  2023      2             kiphire         33949   1.074321e+08

[6512 rows x 6 columns]

In [ ]:
df5.to_csv('g.csv')

In [ ]:
path6='/content/pulse/data/top/user/country/india/state/'
Agg_s6=os.listdir(path6)
Agg_s6

['telangana',
 'karnataka',
 'chhattisgarh',
 'odisha',
 'andaman-&-nicobar-islands',
 'maharashtra',
 'jammu-&-kashmir',
 'west-bengal',
 'uttarakhand',
 'haryana',
 'tamil-nadu',
 'rajasthan',
 'jharkhand',
 'sikkim',
 'andhra-pradesh',
 'kerala',
 'ladakh',
 'madhya-pradesh',
 'chandigarh',
 'meghalaya',
 'uttar-pradesh',
 'lakshadweep',
 'manipur',
 'arunachal-pradesh',
 'punjab',
 'tripura',
 'gujarat',
 'assam',
 'bihar',
 'mizoram',
 'goa',
 'himachal-pradesh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'puducherry',
 'nagaland']

In [ ]:
clm6={'state':[],'year':[],'quter':[],'district_name':[],'registeredUsers':[]}
for s6 in Agg_s6:
  s6_6=path6+s6+'/'
  Agg_y6=os.listdir(s6_6)
  for y6 in Agg_y6:
    y6_6=s6_6+y6+'/'
    Agg_j=os.listdir(y6_6)
    for j in Agg_j:
      j_j=y6_6+j
      dat=open(j_j,'r')
      dd=json.load(dat)
      for h in dd['data']['districts']:
          Name=h['name']
          user=h['registeredUsers']
          clm6['district_name'].append(Name)
          clm6['registeredUsers'].append(user)
          clm6['state'].append(s6)
          clm6['year'].append(y6)
          clm6['quter'].append(int(j.strip('.json')))
df6=pd.DataFrame(clm6)
df6

          state  year  quter       district_name  registeredUsers
0     telangana  2022      4           hyderabad          4962214
1     telangana  2022      4          rangareddy          4296707
2     telangana  2022      4  medchal malkajgiri          3628619
3     telangana  2022      4          sangareddy          1159594
4     telangana  2022      4      warangal urban           923715
...         ...   ...    ...                 ...              ...
6507   nagaland  2023      2            tuensang            15272
6508   nagaland  2023      2                phek            13007
6509   nagaland  2023      2           zunheboto            10327
6510   nagaland  2023      2               peren             7407
6511   nagaland  2023      2             kiphire             6792

[6512 rows x 5 columns]

In [ ]:
df6=df6.to_csv('h.csv')

In [ ]:
df6

In [ ]:
dat=open(j_j,'r')
dd=json.load(dat)
pprint(dd)

{'code': 'SUCCESS',
 'data': {'districts': [{'name': 'gurugram', 'registeredUsers': 2262589},
                        {'name': 'faridabad', 'registeredUsers': 1272506},
                        {'name': 'hisar', 'registeredUsers': 526528},
                        {'name': 'sonipat', 'registeredUsers': 475192},
                        {'name': 'rewari', 'registeredUsers': 453500},
                        {'name': 'panipat', 'registeredUsers': 423131},
                        {'name': 'karnal', 'registeredUsers': 402850},
                        {'name': 'jhajjar', 'registeredUsers': 337303},
                        {'name': 'palwal', 'registeredUsers': 335048},
                        {'name': 'rohtak', 'registeredUsers': 329147}],
          'pincodes': [{'name': '122001', 'registeredUsers': 361360},
                       {'name': '121004', 'registeredUsers': 306230},
                       {'name': '121003', 'registeredUsers': 247955},
                       {'name': '121001', 'registeredUsers': 237542},
                       {'name': '122006', 'registeredUsers': 198022},
                       {'name': '122002', 'registeredUsers': 189395},
                       {'name': '121102', 'registeredUsers': 182342},
                       {'name': '124001', 'registeredUsers': 173733},
                       {'name': '123401', 'registeredUsers': 172665},
                       {'name': '122004', 'registeredUsers': 162301}],
          'states': None},
 'responseTimestamp': 1630501499859,
 'success': True}